version: 0.2

phases:
  pre_build:
    commands:
      - pip install -q --upgrade pip
      - pip install -Iv moto==1.3.14
      - pip install -Iv metadata_parser==0.10.4
      - pip install -q --user pytest boto3 --no-warn-script-location
      - /root/.local/bin/pytest --version
  build:
    commands:
      - /root/.local/bin/pytest --disable-pytest-warnings Tools/tests/
