version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -Iv metadata_parser==0.10.4
      - sam --version
  build:
    commands:
      - cd Tools
      - sam build
      - cd $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - cd Tools
      - sam package --s3-bucket $TOOLS_BUILD_OUTPUT_BUCKET --output-template-file tools-packaged.yaml
      - cd $CODEBUILD_SRC_DIR
artifacts:
  files:
    - Tools/tools-packaged.yaml
  discard-paths: yes
