AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket for storing a services SAM builds. e.g. 'sam-builds-servicename'.  Uses stack name as the bucket name.

Resources:
  TryNewPuzzleBuildsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
